version: '3'

server:
    command: 'php ../../public/index.php'
    env:
        -   APP_RUNTIME: 'Baldinof\RoadRunnerBundle\Runtime\Runtime'

http:
    address: 0.0.0.0:80
    middleware: [ 'static' ]
    static:
        dir: '../../public/'
    pool:
        debug: true
        num_workers: 1
        supervisor:
            max_worker_memory: 110
            exec_ttl: 60s

rpc:
    listen: tcp://0.0.0.0:6001

metrics:
    address: 0.0.0.0:8081

logs:
    mode: development
    level: debug
    output: ../../var/log/rr.log
