stages:
    - deploy

deploy:
    stage: deploy
    before_script:
        - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    after_script:
        - docker logout ${CI_REGISTRY}
    script:
        - make build-prod-image
        - make push-prod-image
        - make deploy
    when: on_success
    only:
        - master
    tags:
        - app-example