services:
    php:
        image: registry.example.com/backend/app-example:prod
        restart: always
        logging:
            driver: loki
            options:
                loki-url: http://172.17.0.1:3100/loki/api/v1/push
        networks:
            - traefik-public
            - default
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public
            - traefik.http.routers.app-example.entryPoints=https
            - traefik.http.routers.app-example.rule=Host(`app-example.example.com`)
            - traefik.http.routers.app-example.tls=true
            - traefik.http.routers.app-example.tls.certResolver=myResolver
            - traefik.http.services.app-example.loadBalancer.server.port=80

networks:
    traefik-public:
        external: true
