version: '3.8'

services:
    php:
        build:
            context: docker/php
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        working_dir: /var/www/html
        tty: true
        extra_hosts:
            - host.docker.internal:host-gateway
        environment:
            COMPOSER_ROOT_VERSION: ${COMPOSER_ROOT_VERSION}
        volumes:
            - .:/var/www/html:cached
            - ~/.composer:/var/www/.composer
        command: sh -c "rr serve -d -c ./docker/php/.rr.yaml"
        labels:
            - traefik.enable=true
            - traefik.http.routers.php.service=php
            - traefik.http.routers.php.entryPoints=https
            - traefik.http.routers.php.rule=Host(`api.app-example.localhost`)
            - traefik.http.routers.php.tls=true
            - traefik.http.services.php.loadBalancer.server.port=80

    traefik:
        image: traefik:v3.0
        command:
            - --api.insecure=true
            - --providers.file.filename=/config/config.toml
            - --providers.docker=true
            - --providers.docker.exposedByDefault=false
            - --entrypoints.http.address=:80
            - --entrypoints.http.http.redirections.entrypoint.to=https
            - --entrypoints.http.http.redirections.entrypoint.scheme=https
            - --entrypoints.https.address=:443
        ports:
            - '443:443'
            - '8080:8080'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./docker/traefik:/config
        labels:
            - traefik.enable=true
            - traefik.http.routers.traefik.entryPoints=https
            - traefik.http.routers.traefik.rule=Host(`traefik.app-example.localhost`)
            - traefik.http.routers.traefik.tls=true
            - traefik.http.services.traefik.loadBalancer.server.port=8080
