apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  labels:
    app.kubernetes.io/component: {{ .Values.service.component }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
    - port: {{ .Values.service.metricsPort }}
      targetPort: {{ .Values.service.metricsTargetPort }}
      protocol: {{ .Values.service.metricsProtocol }}
      name: {{ .Values.service.metricsName }}
  selector:
    app: {{ .Chart.Name }}
