replicaCount: 1

image:
  repository: ci-registry-image
  pullPolicy: IfNotPresent
  tag: "image-version"
  pullSecretName: registry-pull

service:
  component: app-example
  name: http
  port: 80
  targetPort: 8080
  type: ClusterIP
  protocol: TCP
  metricsName: metrics
  metricsPort: 8081
  metricsTargetPort: 8081
  metricsProtocol: TCP

livenessProbe:
  path: /

readinessProbe:
  path: /

resources:
  limits:
    cpu: 1
    memory: 1280Mi
  requests:
    cpu: 1
    memory: 1280Mi


ingress:
  className: nginx
  host: app-example.example.com
  tlsSecret: app-example-tls
  path: /
  pathType: Prefix
